# This is a basic workflow to help you get started with Actions

name: Publish to NPM

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    uses: ./.github/workflows/test.yml
  # This workflow contains a single job called "build"
  publish:
    # The type of runner that the job will run on
    needs: test
    uses: Kingstinct/utils/.github/workflows/publish.yml@main
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
      npm_token: ${{ secrets.npm_token }}
    with:
      description: Autorelease
      release_type: patch
      package_manager: yarn
