# This is a basic workflow to help you get started with Actions

name: Test

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches:
      - "*" # matches every branch that doesn't contain a '/'
      - "*/*" # matches every branch containing a single '/'
      - "**" # matches every branch
      - "!main" # excludes master
      - "!release/production" # excludes master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  cache-warmer:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        id: checkout

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        id: setup
        with:
          cache: yarn
          node-version-file: .nvmrc

      - name: Install deps
        id: install
        if: ${{ steps.setup.outputs.cache-hit == false }}
        run: yarn install --frozen-lockfile

  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: cache-warmer
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        id: setup
        with:
          cache: yarn
          node-version-file: .nvmrc

      - name: Install deps
        run: yarn install --frozen-lockfile --prefer-offline

      - name: Test
        run: yarn test-only

  typecheck:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: cache-warmer
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        id: checkout

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        id: setup
        with:
          cache: yarn
          node-version-file: .nvmrc

      - name: Install deps
        run: yarn install --frozen-lockfile --prefer-offline

      - name: Typecheck
        run: yarn typecheck

  lint:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: cache-warmer
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        id: checkout

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        id: setup
        with:
          cache: yarn
          node-version-file: .nvmrc

      - name: Install deps
        run: yarn install --frozen-lockfile --prefer-offline

      - name: Lint
        run: yarn lint
